[features]
seeds = false
skip-lint = false

[metadata]
anchor_version = "0.31.1"

[programs.localnet]
otakuverse_program = "6WVQUSeRZPpZDukYxKc1gLjG1hRtUMHCGpvoC7vsEFw1"

[programs.devnet]
otakuverse_program = "6WVQUSeRZPpZDukYxKc1gLjG1hRtUMHCGpvoC7vsEFw1"

[programs.testnet]
otakuverse_program = "7VCw2yJjyEY2d68i7QTMSgY6BjSLMdEYPvumorQ5AF99"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "../otakuverse-deployer.json"  # This wallet belongs to Vardan Agarwal

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
